const AUTH = {
  LOGIN: "login/login_performing",
  LOGIN_SUCCESS: "login/login_performed_success",
  LOGIN_FAILURE: "login/login_performed_failure",
  LOGIN_WITH_FB: "login/login_with_fb_performing",
  LOGIN_WITH_FB_SUCCESS: "login/login_with_fb_performed_success",
  LOGIN_WITH_FB_FAILURE: "login/login_with_fb_performed_failure",
  REGISTER: 'register/performing',
  REGISTER_SUCCESS: 'register/success',
  REGISTER_FAILURE: 'register/failure',
  REGISTER_WITH_FB: 'register/performing_registration_with_fb',
  REGISTER_WITH_FB_SUCCESS: 'register/registration_with_fb_success',
  REGISTER_WITH_FB_FAILURE: 'register/registration_with_fb_failure',
  UPDATE_USER_DETAILS: "auth/update_user_details",
  UPDATE_NOTIFICATION_PREFERENCES: 'userpreferences/update-notification-preferences',
  USER_LOGOUT: 'app/user-logout',
  USER_LOGOUT_SUCCESS: 'app/user-logout-success',
  USER_LOGOUT_FAILURE: 'app/user-logout-failure',
  REFRESH_USER_TOKEN: 'login/refresh-user-token',
  REFRESH_USER_TOKEN_SUCCESS: 'login/refresh-user-token-success',
  REFRESH_USER_TOKEN_FAILURE: 'login/refresh-user-token-failure',
  DELETE_USER: 'user/delete',
  DELETE_USER_SUCCESS: 'user/delete-success',
  DELETE_USER_FAILURE: 'user/delete-failure',
  VERIFY_USER_PURCHASE: 'user/verify-purchase',
  VERIFY_USER_PURCHASE_SUCCESS: 'user/verify-purchase-success',
  VERIFY_USER_PURCHASE_FAILURE: 'user/verify-purchase-failure',
  SAVE_NOTIFICATION_TOKEN_ID: 'device/save-notif-device-token-id',
  SAVE_NOTIFICATION_TOKEN_ID_SUCCESS: 'device/save-notif-device-token-id-success',
  SAVE_NOTIFICATION_TOKEN_ID_FAILURE: 'device/save-notif-device-token-id-failure',
  SEND_NOTIFICATION_TOKEN_ID: 'device/send-notif-device-token-id',
  SEND_NOTIFICATION_TOKEN_ID_SUCCESS: 'device/send-notif-device-token-id-success',
  SEND_NOTIFICATION_TOKEN_ID_FAILURE: 'device/send-notif-device-token-id-failure',
};

export default AUTH;
